#!/usr/bin/env sh

source ~/.config/info.sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config layout bsp
# yabai -m config layout float
yabai -m config top_padding 49
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

yabai -m config window_shadow off

yabai -m config auto_balance off
yabai -m config split_ratio 0.50

yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config window_opacity_duration 0.0
yabai -m config normal_window_opacity 0.90

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add title="^kitty-floating$" grid="2:1:12:475:1416:414" opacity=0.90 layer="above" manage=off 
# yabai -m rule --add app="^Finder$" manage=off
# yabai -m rule --add app="^Godot$" manage=off

yabai -m config window_border off
yabai -m config window_border_width 3
yabai -m config window_border_radius 0
yabai -m config active_window_border_color "$yabai_active_border_color"
yabai -m config normal_window_border_color "$yabai_normal_border_color"

# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier fn

# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
