#!/usr/bin/env sh

## HYPER == SHIFT + CMD + ALT + OPTION

hyper - u : yabai -m window --resize bottom:0:20
hyper - i : yabai -m window --resize top:0:-20
hyper - y : yabai -m window --resize left:-20:0
hyper - o : yabai -m window --resize right:20:0

# about spaces
hyper - j : yabai -m space --focus prev || yabai -m space --focus last
hyper - k : yabai -m space --focus next || yabai -m space --focus first

hyper - h : (yabai -m window --space prev || yabai -m window --space last) && (yabai -m space --focus prev || yabai -m space --focus last)
hyper - l : (yabai -m window --space next || yabai -m window --space first) && (yabai -m space --focus next || yabai -m space --focus first)

hyper - c : yabai -m space --create
hyper - d : yabai -m space --destroy

# windows in a space
hyper - r : yabai -m space --rotate 90 # rotate the window tree by 90 degrees 
hyper - e : yabai -m space --balance # balance the window tree

hyper - 0x1E : yabai -m window --focus next # ]
hyper - 0x21 : yabai -m window --focus prev # [

hyper - f : yabai -m window --toggle zoom-fullscreen
hyper - g : yabai -m window --toggle native-fullscreen

hyper - a : yabai -m window --toggle float

# restart
hyper - n : brew services restart yabai
hyper - m : brew services restart sketchybar

# hyper - 1 : python3 ~/kod/bash_scripting/to_study.py
# hyper - 2 : python3 ~/kod/bash_scripting/to_normal.py

hyper - 1 : yabai -m space --focus 1
hyper - 2 : yabai -m space --focus 2
hyper - 3 : yabai -m space --focus 3
hyper - 4 : yabai -m space --focus 4
hyper - 5 : yabai -m space --focus 5
hyper - 6 : yabai -m space --focus 6
hyper - 7 : yabai -m space --focus 7
hyper - 8 : yabai -m space --focus 8
hyper - 9 : yabai -m space --focus 9

# hyper - return : /Users/kutay/.config/kitty/floating_terminal.sh toggle
